Stealth Transactions
OpenBazaar/openbazaar-go pull request #312
Opened 2017-01-09 23:29 UTC by cpacia

2017-01-09 23:37 UTC, jackkleeman commented
Is this aimed at vendors withdrawing money? Very cool.

2017-01-09 23:39 UTC, cpacia commented
It allows someone to send bitcoins to another user's peerID. The coins arrive at a different bitcoin address each time preventing address reuse.

2017-01-09 23:48 UTC, jackkleeman commented
Will this be used as part of the protocol or is it more of an extra useful feature?

2017-01-09 23:55 UTC, cpacia commented
It's only going to be used in the wallet as far as I know.

2017-01-11 10:52 UTC, JustinDrake commented
Can stealth transactions be used for direct OpenBazaar payments (i.e. no moderator)?

2017-01-11 15:17 UTC, cpacia commented
Given that not all wallet implementations can handle stealth transactions (for example bitcoind can't) it's probably not a good idea.

2017-01-11 21:32 UTC, ghost requested changes
Just one small fix, but I think it should be made.

2017-01-11 21:32 UTC, tyler-smith commented on repo/db/keys.go
> +	stmt, err := k.db.Prepare("select key from keys where scriptPubKey=? and purpose=-1")
We should catch this to avoid a nil pointer panic on 121

2017-01-12 02:23 UTC, merged